CREATE TABLE Fog
(
  numer INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nafn VARCHAR(30)
);

CREATE TABLE Afangar
(
  numer INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  audkenni CHAR(7),
  fagNumer INTEGER NOT NULL,
  onn INTEGER,
  FOREIGN KEY (fagNumer) REFERENCES Fog(numer)
);